-- Kathmandu Momo menu seed
-- 1) Upload deploy/menu-pack/menu/* to /home/thehairc/kathmandu-momo/menu/
-- 2) Run this SQL in phpPgAdmin (Postgres)
-- Safe to re-run: clears existing menu categories/items first.

BEGIN;

DELETE FROM menu_item_variants;
DELETE FROM menu_items;
DELETE FROM menu_categories;

-- Reset sequences
ALTER SEQUENCE menu_categories_id_seq RESTART WITH 1;
ALTER SEQUENCE menu_items_id_seq RESTART WITH 1;

INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Snacks', 'Light bites & starters', 1, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Breakfast', 'Morning favourites', 2, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Soups', 'Warm & comforting', 3, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Rice & Noodles', 'Flavourful rice & chow mein', 4, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Chicken', 'Snacks & mains', 5, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Mutton', 'Premium cuts, Nepali style', 6, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Traditional Choila', 'Authentic Nepali delicacy', 7, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Desserts & Ice Cream', 'Sweet endings', 8, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Drinks', 'Refreshing soft drinks & hot beverages', 9, 1);
INSERT INTO menu_categories (name, description, display_order, is_active) VALUES ('Cakes & Pastry', 'Freshly baked daily - 10:00 AM to 10:00 PM', 10, 1);

INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Boil', 'Seasonal vegetables, lightly boiled and seasoned', id, 300, '/uploads/menu/veg-boil.jpg', 1, 1, 1 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Popcorn', 'Crispy buttered corn kernels', id, 150, '/uploads/menu/popcorn.jpg', 1, 1, 2 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Aalo Jeera', 'Cumin-tempered potatoes, Nepali style', id, 180, '/uploads/menu/aalo-jeera.jpg', 1, 1, 3 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Aaloo Sadheko', 'Spiced potato salad with mustard oil & herbs', id, 200, '/uploads/menu/aaloo-sadheko.jpg', 1, 1, 4 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Bhatmas Sadheko', 'Soybeans tossed with spices & chilli', id, 190, '/uploads/menu/bhatmas-sadheko.jpg', 1, 1, 5 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Peanuts Sadheko', 'Roasted peanuts with onion, tomato & spices', id, 220, '/uploads/menu/peanuts-sadheko.jpg', 1, 1, 6 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chips Chilly', 'Crispy potato chips in hot chilli sauce', id, 300, '/uploads/menu/chips-chilly.jpg', 1, 1, 7 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mushroom Chilly', 'Button mushrooms in Indo-Chinese chilli gravy', id, 350, '/uploads/menu/mushroom-chilly.jpg', 1, 1, 8 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Paneer Pakauda', 'Golden-fried cottage cheese fritters', id, 300, '/uploads/menu/paneer-pakauda.jpg', 1, 1, 9 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Pakauda', 'Mixed vegetable fritters, crisp & light', id, 150, '/uploads/menu/veg-pakauda.jpg', 1, 1, 10 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Lasun Poleko', 'Char-grilled garlic, aromatic & bold', id, 170, '/uploads/menu/lasun-poleko.jpg', 1, 1, 11 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Kaju Fry', 'Premium cashews, lightly fried & salted', id, 490, '/uploads/menu/kaju-fry.jpg', 1, 1, 12 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Dry Papad', 'Crisp roasted papad', id, 120, '/uploads/menu/dry-papad.jpg', 1, 1, 13 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Fry Papad', 'Deep-fried papad, extra crunch', id, 180, '/uploads/menu/fry-papad.jpg', 1, 1, 14 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Green Salad', 'Fresh garden greens with house dressing', id, 250, '/uploads/menu/green-salad.jpg', 1, 1, 15 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Fruits Salad', 'Seasonal fruits, lightly chilled', id, 380, '/uploads/menu/fruits-salad.jpg', 1, 1, 16 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Gundruk Sadheko', 'Fermented leafy greens with spice & oil', id, 150, '/uploads/menu/gundruk-sadheko.jpg', 1, 1, 17 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Khaja Set', 'Assorted vegetarian snack platter', id, 250, '/uploads/menu/veg-khaja-set.jpg', 1, 1, 18 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chauchau Sadheko', 'Instant noodles tossed Nepali street style', id, 150, '/uploads/menu/chauchau-sadheko.jpg', 1, 1, 19 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mustang Aalu', 'Spicy mountain-style potato specialty', id, 280, '/uploads/menu/mustang-aalu.jpg', 1, 1, 20 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'French Fries', 'Golden fries with seasoning', id, 200, '/uploads/menu/french-fries.jpg', 1, 1, 21 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chatpate', 'Tangy puffed-rice street snack', id, 120, '/uploads/menu/chatpate.jpg', 1, 1, 22 FROM menu_categories WHERE name = 'Snacks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Sandwich', 'Fresh vegetables between toasted bread', id, 90, '/uploads/menu/veg-sandwich.jpg', 1, 1, 23 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Sandwich', 'Tender chicken filling, lightly toasted', id, 120, '/uploads/menu/chicken-sandwich.jpg', 0, 1, 24 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Burger', 'Crispy veg patty with fresh toppings', id, 150, '/uploads/menu/veg-burger.jpg', 1, 1, 25 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Burger', 'Juicy chicken patty, house sauce', id, 180, '/uploads/menu/chicken-burger.jpg', 0, 1, 26 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Aalu Paratha', 'Served with pickle & curd', id, 150, '/uploads/menu/aalu-paratha.jpg', 1, 1, 27 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Plain Paratha Set', '3 pcs with veg aalu matar', id, 130, '/uploads/menu/plain-paratha-set.jpg', 1, 1, 28 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Grand Breakfast Combo', 'Sausage, 2 boiled eggs, sandwich or 2 aalu paratha', id, 300, '/uploads/menu/grand-breakfast-combo.jpg', 0, 1, 29 FROM menu_categories WHERE name = 'Breakfast';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Manchow Soup', 'Indo-Chinese vegetable soup with crunch', id, 120, '/uploads/menu/veg-manchow-soup.jpg', 1, 1, 30 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mushroom Soup', 'Creamy mushroom broth', id, 150, '/uploads/menu/mushroom-soup.jpg', 1, 1, 31 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Hot and Sour Soup', 'Tangy and spicy classic', id, 160, '/uploads/menu/hot-and-sour-soup.jpg', 1, 1, 32 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Tomato Cream Soup', 'Silky tomato cream, herb finish', id, 160, '/uploads/menu/tomato-cream-soup.jpg', 1, 1, 33 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Manchow Soup', 'Hearty chicken manchow with fried noodles', id, 160, '/uploads/menu/chicken-manchow-soup.jpg', 0, 1, 34 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Local Chicken Soup', 'Traditional clear local chicken broth', id, 220, '/uploads/menu/local-chicken-soup.jpg', 0, 1, 35 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Soup', 'Rich mutton broth, slow simmered', id, 200, '/uploads/menu/mutton-soup.jpg', 0, 1, 36 FROM menu_categories WHERE name = 'Soups';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Fried Rice', 'Wok-tossed rice with fresh vegetables', id, 150, '/uploads/menu/veg-fried-rice.jpg', 1, 1, 37 FROM menu_categories WHERE name = 'Rice & Noodles';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Egg Fried Rice', 'Classic fried rice with scrambled egg', id, 200, '/uploads/menu/egg-fried-rice.jpg', 0, 1, 38 FROM menu_categories WHERE name = 'Rice & Noodles';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Fried Rice', 'Chicken pieces tossed with fragrant rice', id, 180, '/uploads/menu/chicken-fried-rice.jpg', 0, 1, 39 FROM menu_categories WHERE name = 'Rice & Noodles';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mixed Fried Rice', 'Combination fried rice, full flavour', id, 220, '/uploads/menu/mixed-fried-rice.jpg', 0, 1, 40 FROM menu_categories WHERE name = 'Rice & Noodles';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Veg Chow Mein', 'Stir-fried noodles with garden vegetables', id, 160, '/uploads/menu/veg-chow-mein.jpg', 1, 1, 41 FROM menu_categories WHERE name = 'Rice & Noodles';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Chow Mein', 'Wok-fried noodles with chicken', id, 200, '/uploads/menu/chicken-chow-mein.jpg', 0, 1, 42 FROM menu_categories WHERE name = 'Rice & Noodles';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Roast', 'Slow-roasted chicken, aromatic spices', id, 200, '/uploads/menu/chicken-roast.jpg', 0, 1, 43 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Boil', 'Gently boiled chicken, clean & tender', id, 250, '/uploads/menu/chicken-boil.jpg', 0, 1, 44 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Lollipop', 'Crispy lollipop-cut wings', id, 280, '/uploads/menu/chicken-lollipop.jpg', 0, 1, 45 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Chilly', 'Indo-Chinese chilli chicken', id, 260, '/uploads/menu/chicken-chilly.jpg', 0, 1, 46 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Fry Sadheko', 'Fried chicken tossed with Nepali spices', id, 270, '/uploads/menu/chicken-fry-sadheko.jpg', 0, 1, 47 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Wings', 'Crispy wings with house seasoning', id, 380, '/uploads/menu/chicken-wings.jpg', 0, 1, 48 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Timur (Szechuan)', 'Sichuan pepper chicken, numbing heat', id, 300, '/uploads/menu/chicken-timur-szechuan.jpg', 0, 1, 49 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Sekuwa', 'Charcoal-grilled chicken skewers', id, 200, '/uploads/menu/chicken-sekuwa.jpg', 0, 1, 50 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chicken Sausage', 'Grilled chicken sausage', id, 200, '/uploads/menu/chicken-sausage.jpg', 0, 1, 51 FROM menu_categories WHERE name = 'Chicken';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Bhutan', 'Spicy dry mutton with chilli', id, 250, '/uploads/menu/mutton-bhutan.jpg', 0, 1, 52 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Kan Jibro', 'Traditional offal specialty', id, 350, '/uploads/menu/kan-jibro.jpg', 0, 1, 53 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Sekuwa', 'Charcoal-grilled mutton skewers', id, 480, '/uploads/menu/mutton-sekuwa.jpg', 0, 1, 54 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Pakku', 'Slow-cooked spicy mutton curry', id, 450, '/uploads/menu/mutton-pakku.jpg', 0, 1, 55 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Tas', 'Tender mutton tas preparation', id, 400, '/uploads/menu/mutton-tas.jpg', 0, 1, 56 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Polera', 'Grilled mutton, house spices', id, 420, '/uploads/menu/mutton-polera.jpg', 0, 1, 57 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Fry Sadheko', 'Fried mutton tossed with spices', id, 380, '/uploads/menu/mutton-fry-sadheko.jpg', 0, 1, 58 FROM menu_categories WHERE name = 'Mutton';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Local Chicken Choila', 'Spiced local chicken choila', id, 330, '/uploads/menu/local-chicken-choila.jpg', 0, 1, 59 FROM menu_categories WHERE name = 'Traditional Choila';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Local Chicken Choila Poleko', 'Char-grilled local chicken choila', id, 380, '/uploads/menu/local-chicken-choila-poleko.jpg', 0, 1, 60 FROM menu_categories WHERE name = 'Traditional Choila';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Duck (Has) Choila Fry', 'Fried duck choila', id, 350, '/uploads/menu/duck-has-choila-fry.jpg', 0, 1, 61 FROM menu_categories WHERE name = 'Traditional Choila';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Duck (Has) Choila Poleko', 'Char-grilled duck choila', id, 400, '/uploads/menu/duck-has-choila-poleko.jpg', 0, 1, 62 FROM menu_categories WHERE name = 'Traditional Choila';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton Choila Fry', 'Fried mutton choila', id, 400, '/uploads/menu/mutton-choila-fry.jpg', 0, 1, 63 FROM menu_categories WHERE name = 'Traditional Choila';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mutton (Poleko) Choila', 'Char-grilled mutton choila', id, 450, '/uploads/menu/mutton-poleko-choila.jpg', 0, 1, 64 FROM menu_categories WHERE name = 'Traditional Choila';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Vanilla Ice Cream', 'Classic vanilla scoop', id, 85, '/uploads/menu/vanilla-ice-cream.jpg', 1, 1, 65 FROM menu_categories WHERE name = 'Desserts & Ice Cream';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chocolate Ice Cream', 'Rich chocolate scoop', id, 90, '/uploads/menu/chocolate-ice-cream.jpg', 1, 1, 66 FROM menu_categories WHERE name = 'Desserts & Ice Cream';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Strawberry Ice Cream', 'Fruity strawberry scoop', id, 90, '/uploads/menu/strawberry-ice-cream.jpg', 1, 1, 67 FROM menu_categories WHERE name = 'Desserts & Ice Cream';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Pineapple Ice Cream', 'Tropical pineapple scoop', id, 95, '/uploads/menu/pineapple-ice-cream.jpg', 1, 1, 68 FROM menu_categories WHERE name = 'Desserts & Ice Cream';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Butterscotch Ice Cream', 'Butterscotch swirl scoop', id, 95, '/uploads/menu/butterscotch-ice-cream.jpg', 1, 1, 69 FROM menu_categories WHERE name = 'Desserts & Ice Cream';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Mineral Water', 'Bottled drinking water', id, 35, '/uploads/menu/mineral-water.jpg', 1, 1, 70 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Coke / Fanta / Sprite / Soda', 'Chilled soft drink (regular)', id, 85, '/uploads/menu/coke-fanta-sprite-soda.jpg', 1, 1, 71 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Red Bull', 'Energy drink', id, 200, '/uploads/menu/red-bull.jpg', 1, 1, 72 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Fresh Lime Soda', 'Fresh lime with soda', id, 100, '/uploads/menu/fresh-lime-soda.jpg', 1, 1, 73 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Real Juice', 'Real juice — small Rs 100 / jumbo Rs 425', id, 100, '/uploads/menu/real-juice.jpg', 1, 1, 74 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Jumbo Coke', 'Large bottle soft drink', id, 425, '/uploads/menu/jumbo-coke.jpg', 1, 1, 75 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Black Tea', 'Hot black tea', id, 40, '/uploads/menu/black-tea.jpg', 1, 1, 76 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Milk Tea', 'Classic milk tea', id, 60, '/uploads/menu/milk-tea.jpg', 1, 1, 77 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Black Coffee', 'Hot black coffee', id, 90, '/uploads/menu/black-coffee.jpg', 1, 1, 78 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Milk Coffee', 'Coffee with milk', id, 100, '/uploads/menu/milk-coffee.jpg', 1, 1, 79 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Hot Lemon with Honey', 'Warm lemon honey drink', id, 185, '/uploads/menu/hot-lemon-with-honey.jpg', 1, 1, 80 FROM menu_categories WHERE name = 'Drinks';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Black Forest (1 lb)', 'Classic black forest cake, 1 lb', id, 650, '/uploads/menu/black-forest-1-lb.jpg', 1, 1, 81 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'White Forest (1 lb)', 'White forest cake, 1 lb', id, 650, '/uploads/menu/white-forest-1-lb.jpg', 1, 1, 82 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Strawberry (1 lb)', 'Strawberry cake, 1 lb', id, 650, '/uploads/menu/strawberry-1-lb.jpg', 1, 1, 83 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chocolate Cake (1 lb)', 'Rich chocolate cake, 1 lb', id, 900, '/uploads/menu/chocolate-cake-1-lb.jpg', 1, 1, 84 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Red Velvet (1 lb)', 'Red velvet cake, 1 lb', id, 1100, '/uploads/menu/red-velvet-1-lb.jpg', 1, 1, 85 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Cheesecake (1 lb)', 'Creamy cheesecake, 1 lb', id, 1500, '/uploads/menu/cheesecake-1-lb.jpg', 1, 1, 86 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Black Forest Pastry', 'Single-serve black forest pastry', id, 70, '/uploads/menu/black-forest-pastry.jpg', 1, 1, 87 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'White Forest Pastry', 'Single-serve white forest pastry', id, 80, '/uploads/menu/white-forest-pastry.jpg', 1, 1, 88 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Strawberry Pastry', 'Single-serve strawberry pastry', id, 110, '/uploads/menu/strawberry-pastry.jpg', 1, 1, 89 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Chocolate Pastry', 'Single-serve chocolate pastry', id, 140, '/uploads/menu/chocolate-pastry.jpg', 1, 1, 90 FROM menu_categories WHERE name = 'Cakes & Pastry';
INSERT INTO menu_items (name, description, category_id, base_price, image_url, is_vegetarian, is_available, display_order) SELECT 'Cheesecake Pastry', 'Single-serve cheesecake pastry', id, 220, '/uploads/menu/cheesecake-pastry.jpg', 1, 1, 91 FROM menu_categories WHERE name = 'Cakes & Pastry';

COMMIT;

-- Verify: SELECT c.name, COUNT(i.id) FROM menu_categories c LEFT JOIN menu_items i ON i.category_id = c.id GROUP BY c.name ORDER BY MIN(c.display_order);
